//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by script1.rc
//
#define IDS_STRING1                     1
#define IDS_STRING2                     2
#define IDD_DIALOG1                     101
#define IDR_MENU1                       102
#define IDD_DIALOG2                     103
#define IDD_DIALOG3                     104
#define IDD_DIALOG4                     112
#define IDD_DIALOG5                     118
#define IDC_LIST1                       1015
#define IDC_LIST2                       1019
#define IDC_CHECK1                      1023
#define ID_PERSPECTVE                   10000
#define ID_ORTHO                        10001
#define ID_XY                           10002
#define ID_YZ                           10003
#define ID_ZX                           10004
#define ID_ABOUT                        40005
#define ID_MODEL                        40008
#define ID_EXIT                         65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1024
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
